describe('Registro de Usuario', () => {
    
    beforeEach(() => {
        cy.visit('https://ticketazo.com.ar/auth/registerUser')
    })

    it('Campo obligatorio vacío', () => {
        cy.get('[data-cy="input-nombres"]').type('Francisco')
        cy.get('[data-cy="input-apellido"]').type('Bruno')
        cy.get('[data-cy="input-telefono"]').type('3533454545')
        cy.get('[data-cy="input-dni"]').type('12345678')
        cy.get('[data-cy="select-provincia"]').click()
        cy.get('[data-cy="select-provincia"]').type('Cordoba{enter}')
        cy.get('[data-cy="select-localidad"]').click()
        cy.get('[data-cy="select-localidad"]').type('Las Varil{enter}')
        cy.get('[data-cy="input-email"]').type('franb@fran.com')
        cy.get('[data-cy="input-confirmar-email"]').type('franb@fran.com')
        cy.get('[data-cy="input-password"]').type('franb1234')
        cy.get('[data-cy="input-repetir-password"]').type('franb1234')
        cy.get('button[type="submit"]').click()
        cy.contains('Completa este campo').should('be.visible')
  })

    it('Emails distintos', () => {
        cy.get('[data-cy="input-nombres"]').type('Francisco')
        cy.get('[data-cy="input-apellido"]').type('Bruno')
        cy.get('[data-cy="input-telefono"]').type('3533454545')
        cy.get('[data-cy="input-dni"]').type('12345678')
        cy.get('[data-cy="select-provincia"]').click()
        cy.get('[data-cy="select-provincia"]').type('Cordoba{enter}')
        cy.get('[data-cy="select-localidad"]').click()
        cy.get('[data-cy="select-localidad"]').type('Las Varil{enter}')
        cy.contains('dd').type('07')
        cy.contains('mm').type('05')
        cy.contains('aaaa').type('1995')
        cy.get('[data-cy="input-email"]').type('franb@fran.com')
        cy.get('[data-cy="input-confirmar-email"]').type('fran@fran.com')
        cy.get('[data-cy="input-password"]').type('franb1234')
        cy.get('[data-cy="input-repetir-password"]').type('franb1234')
        cy.get('button[type="submit"]').click()
        cy.get('[data-cy="error-message"]').should('have.text', 'Los correos electrónicos no coinciden')
    })

    it('Contraseñas distintas', () => {
        cy.get('[data-cy="input-nombres"]').type('Francisco')
        cy.get('[data-cy="input-apellido"]').type('Bruno')
        cy.get('[data-cy="input-telefono"]').type('3533454545')
        cy.get('[data-cy="input-dni"]').type('12345678')
        cy.get('[data-cy="select-provincia"]').click()
        cy.get('[data-cy="select-provincia"]').type('Cordoba{enter}')
        cy.get('[data-cy="select-localidad"]').click()
        cy.get('[data-cy="select-localidad"]').type('Las Varil{enter}')
        cy.contains('dd').type('07')
        cy.contains('mm').type('05')
        cy.contains('aaaa').type('1995')
        cy.get('[data-cy="input-email"]').type('franb@fran.com')
        cy.get('[data-cy="input-confirmar-email"]').type('franb@fran.com')
        cy.get('[data-cy="input-password"]').type('franb1234')
        cy.get('[data-cy="input-repetir-password"]').type('franb1235')
        cy.get('button[type="submit"]').click()
        cy.get('[data-cy="error-message"]').should('have.text', 'Las contraseñas no coinciden')
    })

    it('Contraseña invalida', () => {
        cy.get('[data-cy="input-nombres"]').type('Francisco')
        cy.get('[data-cy="input-apellido"]').type('Bruno')
        cy.get('[data-cy="input-telefono"]').type('3533454545')
        cy.get('[data-cy="input-dni"]').type('12345678')
        cy.get('[data-cy="select-provincia"]').click()
        cy.get('[data-cy="select-provincia"]').type('Cordoba{enter}')
        cy.get('[data-cy="select-localidad"]').click()
        cy.get('[data-cy="select-localidad"]').type('Las Varil{enter}')
        cy.contains('dd').type('07')
        cy.contains('mm').type('05')
        cy.contains('aaaa').type('1995')
        cy.get('[data-cy="input-email"]').type('franb@fran.com')
        cy.get('[data-cy="input-confirmar-email"]').type('franb@fran.com')
        cy.get('[data-cy="input-password"]').type('franb1234')
        cy.get('[data-cy="input-repetir-password"]').type('franb1234')
        cy.get('button[type="submit"]').click()
        cy.get('[data-cy="error-message"]').should('have.text', 'La contraseña debe tener al menos 8 caracteres, incluyendo mayúsculas, minúsculas, números y símbolos.')
    })

    it('Error formato DNI', () => {
        cy.get('[data-cy="input-nombres"]').type('Francisco')
        cy.get('[data-cy="input-apellido"]').type('Bruno')
        cy.get('[data-cy="input-telefono"]').type('3533454545')
        cy.get('[data-cy="input-dni"]').type('1234567')
        cy.get('[data-cy="select-provincia"]').click()
        cy.contains('Utiliza un formato que coincida con el solicitado').should('be.visible')
        cy.get('[data-cy="select-provincia"]').type('Cordoba{enter}')
        cy.get('[data-cy="select-localidad"]').click()
        cy.get('[data-cy="select-localidad"]').type('Las Varil{enter}')
        cy.contains('dd').type('07')
        cy.contains('mm').type('05')
        cy.contains('aaaa').type('1995')
        cy.get('[data-cy="input-email"]').type('franb@fran.com')
        cy.get('[data-cy="input-confirmar-email"]').type('franb@fran.com')
        cy.get('[data-cy="input-password"]').type('Franb1234!')
        cy.get('[data-cy="input-repetir-password"]').type('Franb1234!')
    })

    it('Error formato telefono', () => {
        cy.get('[data-cy="input-nombres"]').type('Francisco')
        cy.get('[data-cy="input-apellido"]').type('Bruno')
        cy.get('[data-cy="input-telefono"]').type('123')
        cy.get('[data-cy="input-dni"]').type('12345679')
        cy.contains('Utiliza un formato que coincida con el solicitado').should('be.visible')
        cy.get('[data-cy="select-provincia"]').click()
        cy.get('[data-cy="select-provincia"]').type('Cordoba{enter}')
        cy.get('[data-cy="select-localidad"]').click()
        cy.get('[data-cy="select-localidad"]').type('Las Varil{enter}')
        cy.contains('dd').type('07')
        cy.contains('mm').type('05')
        cy.contains('aaaa').type('1995')
        cy.get('[data-cy="input-email"]').type('franb@fran.com')
        cy.get('[data-cy="input-confirmar-email"]').type('franb@fran.com')
        cy.get('[data-cy="input-password"]').type('Franb1234!')
        cy.get('[data-cy="input-repetir-password"]').type('Franb1234!')
    })

    it('Usuario ya registrado', () => {
        cy.get('[data-cy="input-nombres"]').type('Francisco')
        cy.get('[data-cy="input-apellido"]').type('Bruno')
        cy.get('[data-cy="input-telefono"]').type('3533454545')
        cy.get('[data-cy="input-dni"]').type('12345678')
        cy.get('[data-cy="select-provincia"]').click()
        cy.get('[data-cy="select-provincia"]').type('Cordoba{enter}')
        cy.get('[data-cy="select-localidad"]').click()
        cy.get('[data-cy="select-localidad"]').type('Las Varil{enter}')
        cy.contains('dd').type('07')
        cy.contains('mm').type('05')
        cy.contains('aaaa').type('1995')
        cy.get('[data-cy="input-email"]').type('franb@fran.com')
        cy.get('[data-cy="input-confirmar-email"]').type('franb@fran.com')
        cy.get('[data-cy="input-password"]').type('Franb1234!')
        cy.get('[data-cy="input-repetir-password"]').type('Franb1234!')
        cy.get('button[type="submit"]').click()
        cy.get('[data-cy="error-message"]').should('have.text', 'Ya existe un usuario registrado con ese DNI')
    })

    ('Registro exitoso', () => {
        cy.get('[data-cy="input-nombres"]').type('Francisco')
        cy.get('[data-cy="input-apellido"]').type('Bruno')
        cy.get('[data-cy="input-telefono"]').type('3533454545')
        cy.get('[data-cy="input-dni"]').type('35345679')
        cy.get('[data-cy="select-provincia"]').click()
        cy.get('[data-cy="select-provincia"]').type('Cordoba{enter}')
        cy.get('[data-cy="select-localidad"]').click()
        cy.get('[data-cy="select-localidad"]').type('Las Varil{enter}')
        cy.contains('dd').type('07')
        cy.contains('mm').type('05')
        cy.contains('aaaa').type('1995')
        cy.get('[data-cy="input-email"]').type('franb@fran.com')
        cy.get('[data-cy="input-confirmar-email"]').type('franb@fran.com')
        cy.get('[data-cy="input-password"]').type('Franb1234!')
        cy.get('[data-cy="input-repetir-password"]').type('Franb1234!')
        cy.get('button[type="submit"]').click()
    })
})